### PR TITLE
Unvendor ipaddress module (Closes #9)

### LINKED ISSUE #9: Unvendor ipaddress module
I don't know what I was thinking. There's no reason for this to be vendored, and the code to vendor it is gnarly.

### PR DESCRIPTION
**Pull request by ColdHeat**
* Remove `advocate.packages` and instead install `py2-ipaddress`
* Only install `py2-ipaddress` if being installed on Python < 3.3
* Closes #9 

This shouldn't break Py2 compatibility but I had some trouble getting tests running so I'm not 100% sure but I imagine it's fine. Also not sure if Travis still has a free tier?

### CODE REVIEW

**Comment by ColdHeat** [comment]
If it's a concern, this commit appears to be the only new one since the py2-ipaddress module was vendored: https://github.com/kwi-dk/py2-ipaddress/commit/117fc9bbcac487b7f781841a7b6c5c6bfaa867ef

**Comment by ColdHeat** [comment]
@JordanMilne, tests seem to pass on all supported versions. Seems safe to merge and release as `v1.1.0`?

**Comment by JordanMilne** [comment]
Thanks for this, this is great!

@spladug Do you think I should switch this to use https://github.com/phihag/ipaddress at the same time? Py2 code would have to be changed to use `unicode` strings, but the package is already in r2's requirements. The previously-vendored `py2-ipaddress` _also_ provides `ipaddress`, so it might conflict if I don't switch.

**Comment by spladug** [comment]
That'd probably work! Alternatively, I think it'd be reasonable to drop Py2 support here and if really necessary keep it around on a branch only. That'd probably simplify maintenance quite a bit.

**Comment by ColdHeat** [comment]
Not sure what the benefit would be of switching to https://github.com/phihag/ipaddress? Maybe just b/c that library is closer to the actual one in Python 3?  

Both libraries seem to create an ipaddress module. `py2-ipaddress` won't even install for me on 3.x. `ipaddress` (the pip one), you can't  import instead of the built-in one in Python 3. 

If internally you're using all Python 3 then perhaps just drop Python 2 support entirely and release `2.0.0`?

**Comment by ColdHeat** [comment]
@JordanMilne any chance this can be merged? Would like to use this through PyPI if possible.

**Pull request merged**
